# Generated by Django 6.0.2 on 2026-02-08 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minamo', '0002_book_chapter_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
