# Generated by Django 6.0.2 on 2026-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minamo', '0003_book_created_date_alter_book_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
