# Generated by Django 6.0.2 on 2026-02-10 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minamo', '0004_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='section',
            name='created_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
