# Generated by Django 6.0.2 on 2026-02-10 23:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minamo', '0005_chapter_created_date_chapter_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='next_chapter_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chapter',
            name='next_section_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
