# Generated by Django 6.0.2 on 2026-02-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minamo', '0006_book_next_chapter_order_chapter_next_section_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(default='New Section', max_length=200),
        ),
    ]
