# Generated by Django 6.0.2 on 2026-02-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minamo', '0007_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content_head',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
