# Generated by Django 6.0.2 on 2026-02-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minamo', '0009_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
