# Generated by Django 6.0.2 on 2026-02-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minamo', '0010_book_length_chapter_length_section_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='UD_Digi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='text_vertical_align',
            field=models.BooleanField(default=False),
        ),
    ]
